#!/bin/bash

# If bind is found running then add optional packages for extend-bind.pl

# Copyright (C) 2020 Joseph Tingiris (joseph.tingiris@gmail.com)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Dependencies:
# setup-snmpd
# pidof

#
# 20200201, joseph.tingiris@gmail.com, created
#

if [ "${0}" == "${BASH_SOURCE}" ]; then
    printf "\naborting ... this script was executed, it must be sourced\n\n"; exit 1
fi

# needed for extend-bind.pl
if [ -f /etc/named.conf ]; then
    if pidof bind &> /dev/null; then
        debugecho "bind is running" 5
        Extend_Bind_RC=1
        if [ -f "${Dirname}/librenms/extend-bind.pl" ]; then
            if [ -f "${Dirname}/librenms/extend-bind.conf" ]; then
                Extend_Bind_Args="-c ${Dirname}/librenms/extend-bind.conf"
            fi

            bash "${Dirname}/librenms/extend-bind.pl" ${Extend_Bind_Args} &> /dev/null
            Extend_Bind_RC=$?
        fi

        if [ ${Extend_Bind_RC} -eq 0 ]; then
            _echo "extend bind stats" OK
        else
            _echo "extend bind stats failed" WARNING
            Optional_Packages+=(perl perl-File-ReadBackwards)
        fi
    else
        debugecho "bind is not running" 5
    fi
else
    debugecho "/etc/named.conf file not found" 5
fi
