---
# file: roles/setup_snmpd/tasks/main.yml

- name: "set setup_snmpd_archive"
  set_fact:
    setup_snmpd_archive: /opt/librenms/etc/snmp/.ansible/files/setup_snmpd/setup_snmpd.tar.gz

- name: "fail when setup_snmpd_archive is not defined"
  fail:
    msg: "setup_snmpd_archive is not defined"
  when:
    - setup_snmpd_archive is not defined

- name: "set setup_snmpd_dir"
  set_fact:
    setup_snmpd_dir: /var/tmp/setup-snmpd-ansible

- name: "fail when setup_snmpd_dir is not defined"
  fail:
    msg: "setup_snmpd_dir is not defined"
  when:
    - setup_snmpd_dir is not defined

#
# check or install
#

- name: "remove {{ setup_snmpd_dir }}"
  changed_when: false
  file:
    path: "{{ setup_snmpd_dir }}"
    state: absent
  when:
    - setup_snmpd_action != "upgrade"

- name: "validate {{ setup_snmpd_dir }}"
  changed_when: false
  file:
    path: "{{ setup_snmpd_dir }}"
    state: directory
  when:
    - setup_snmpd_action != "upgrade"

- name: "untar /var/tmp/setup_snmpd.tar.gz to {{ setup_snmpd_dir }}"
  changed_when: false
  unarchive:
    src: "{{ setup_snmpd_archive }}"
    dest: "{{ setup_snmpd_dir }}"
    owner: root
    group: root
  when:
    - setup_snmpd_action != "upgrade"

- name: "stat {{ setup_snmpd_dir}}/setup-snmpd"
  register: stat_setup_snmpd
  stat:
    path: "{{ setup_snmpd_dir }}/setup-snmpd"
  when:
    - setup_snmpd_action != "upgrade"

- name: "[check] execute {{ setup_snmpd_dir }}/setup-snmpd check"
  shell: "{{ setup_snmpd_dir }}/setup-snmpd check 2>&1 | tee /var/tmp/ansible-snmpd-check.log"
  become: true
  become_user: root
  register: check_setup_snmpd_result
  failed_when: "check_setup_snmpd_result.rc != 0"
  changed_when: '"NOTICE" in check_setup_snmpd_result.stdout'
  when:
    - setup_snmpd_action != "upgrade"
    - stat_setup_snmpd.stat.executable

- name: "debug output for {{ setup_snmpd_dir }}/setup-snmpd check"
  debug:
    var: check_setup_snmpd_result
    verbosity: 2
  when:
    - setup_snmpd_action != "upgrade"

- name: "remove {{ setup_snmpd_dir }}"
  changed_when: false
  file:
    path: "{{ setup_snmpd_dir }}"
    state: absent
  when:
    - setup_snmpd_action != "upgrade"

#
# install or upgrade
#

- name: "[{{ setup_snmpd_action }}] set install_setup_snmpd_dir"
  set_fact:
    install_setup_snmpd_dir: /etc/snmp

- name: "[{{ setup_snmpd_action }}] fail when install_setup_snmpd_dir is not defined"
  fail:
    msg: "install_setup_snmpd_dir is not defined"
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - install_setup_snmpd_dir is not defined

- name: "[{{ setup_snmpd_action }}] stat {{ install_setup_snmpd_dir }}"
  register: stat_etc_snmp
  stat:
    path: "{{ install_setup_snmpd_dir }}"
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - check_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"

- name: "[{{ setup_snmpd_action }}] backup /etc/snmp/snmpd.conf to /var/tmp/setup-snmpd-ansible.conf.bak"
  copy: src=/etc/snmp/snmpd.conf dest=/var/tmp/setup-snmpd-ansible.conf.bak owner=root group=root mode=0640 backup=yes remote_src=yes
  register: result_backup_snmpd_conf
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - check_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"
    - stat_etc_snmp.stat.exists

- name: "[{{ setup_snmpd_action }}] remove {{ install_setup_snmpd_dir }}"
  changed_when: false
  file:
    path: "{{ install_setup_snmpd_dir }}"
    state: absent
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - check_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"

- name: "[{{ setup_snmpd_action }}] validate {{ install_setup_snmpd_dir }}"
  changed_when: false
  file:
    path: "{{ install_setup_snmpd_dir }}"
    state: directory
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - check_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"

- name: "[{{ setup_snmpd_action }}] untar /var/tmp/setup_snmpd.tar.gz to {{ install_setup_snmpd_dir }}"
  changed_when: false
  unarchive:
    src: "{{ setup_snmpd_archive }}"
    dest: "{{ install_setup_snmpd_dir }}"
    owner: root
    group: root
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - check_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"

- name: "[{{ setup_snmpd_action }}] stat {{ install_setup_snmpd_dir}}/setup-snmpd"
  register: stat_install_setup_snmpd
  stat:
    path: "{{ install_setup_snmpd_dir }}/setup-snmpd"
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - check_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"

- name: "[{{ setup_snmpd_action }}] execute {{ install_setup_snmpd_dir }}/setup-snmpd install"
  shell: "{{ install_setup_snmpd_dir }}/setup-snmpd install 2>&1 | tee /var/tmp/ansible-snmpd-install.log"
  become: true
  become_user: root
  register: install_setup_snmpd_result
  failed_when: "install_setup_snmpd_result.rc != 0"
  changed_when: '"NOTICE" in install_setup_snmpd_result.stdout'
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - check_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"
    - stat_install_setup_snmpd.stat.executable

- name: "[{{ setup_snmpd_action }}] debug output for {{ install_setup_snmpd_dir }}/setup-snmpd install"
  debug:
    var: install_setup_snmpd_result
    verbosity: 2
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"

- name: "restart snmpd service"
  service:
    name: snmpd
    state: restarted
  when:
    - setup_snmpd_action == "install" or setup_snmpd_action == "upgrade"
    - check_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"
    - install_setup_snmpd_result.changed or setup_snmpd_action == "upgrade"
